[metadata]
name = ultimate-gau
version = 3.0.0
author = ssecgroup_shiyanthan_k
author_email = ssecgroup08@gmail.com
description = Ultimate GAU - Get All URLs from multiple free web archives
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/ssecgroup/ultimate-gau
project_urls =
    Bug Tracker = https://github.com/ssecgroup/ultimate-gau/issues
    Documentation = https://github.com/ssecgroup/ultimate-gau#readme
    Source Code = https://github.com/ssecgroup/ultimate-gau
    Donate = https://github.com/ssecgroup/ultimate-gau#support-the-project
classifiers =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    Topic :: Security
    Topic :: Internet :: WWW/HTTP
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.7
install_requires =
    requests>=2.25.0
    urllib3>=1.26.0
include_package_data = True
zip_safe = False

[options.entry_points]
console_scripts =
    ugau = ultimate_gau.cli:main
    ultimate-gau = ultimate_gau.cli:main

[options.extras_require]
progress = 
    tqdm>=4.62.0
validation = 
    validators>=0.18.0
all = 
    tqdm>=4.62.0
    validators>=0.18.0
dev = 
    pytest>=6.2.5
    black>=21.9b0
    flake8>=3.9.2
    mypy>=0.910

[options.packages.find]
exclude =
    tests*
    docs*
